# permissions for end users to edit capps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capp-editor-role
rules:
- apiGroups:
  - rcs.dana.io
  resources:
  - capps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rcs.dana.io
  resources:
  - capps/status
  verbs:
  - get
