# permissions for end users to view capps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capp-viewer-role
rules:
- apiGroups:
  - rcs.dana.io
  resources:
  - capps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rcs.dana.io
  resources:
  - capps/status
  verbs:
  - get
