kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: klusterlet-work-sa-capp-target
rules:
  - verbs:
      - create
      - update
      - patch
      - delete
      - get
      - list
      - watch
    apiGroups:
      - rcs.dana.io
    resources:
      - capps
  - verbs:
      - update
    apiGroups:
      - rcs.dana.io
    resources:
      - capps/finalizers
  - verbs:
      - get
    apiGroups:
      - rcs.dana.io
    resources:
      - capps/status
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - serving.knative.dev
    resources:
      - services