apiVersion: rcs.dana.io/v1alpha1
kind: Capp
metadata:
  name: koki
spec:
  configurationSpec:
    template:
      metadata:
        creationTimestamp: null
      spec:
        containers:
        - env:
          - name: APP_NAME
            value: capp-with-cluster
          image: sahar2339/example-python-app:v1-flask
          name: capp-with-cluster
          resources: {}
  routeSpec:
    hostname: rbacqwegen.dev
  scaleMetric: cpu
